---
applications:
- name: node
  command: ./geth --networkid="12345" --bootnodes=enode://$BOOTNODE_PUBKEY@$BOOTNODE_IP:33445 --datadir="./data" --nat none -verbosity 6
  health-check-type: process
  buildpack: binary_buildpack
  no-route: true
