---
applications:
- name: node
  command: source node_env.sh && ./geth --networkid=$NETWORK_ID --rpc --rpcaddr 0.0.0.0 --rpcport $PORT --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --bootnodes=enode://$BOOTNODE --datadir="./data" --nat none -verbosity 6
  health-check-type: process
  buildpack: binary_buildpack
  no-route: true
  services:
    - ethereum-discovery
